version: "3"
services:
  EbookStore_database:
   image: "mongo:latest"
   container_name: "EbookStore_database"
   ports: 
   - 27017:27017
   
  Ebook.SpringApp:
    image: "Ebook:SpringApp"
    container_name: "Ebook.SpringApp"
    ports:
    - 8080:8080
    
    
  Ebook.ReactApp:
     image: "Ebook:ReactApp"  
     container_name: "Ebook.ReactApp"
     ports:
     - 3000:3000  
     links:
     - Ebook.ReactApp 
     - Ebook.SpringApp
