version: "3"
services:
  mymongodb:
   image: mongo:latest
   container_name: "mymongodb"
   ports: 
   - 27017:27017
   
  ebook.springapp:
    image: "springboot-mongodb:1.0"
    container_name: "springapp"
    ports:
    - 8080:8080
    
    
  react_ebook:
     image: "react-app:dev"  
     container_name: "frontend"
     ports:
     - 3000:3000  
     links:
     - mymongodb 
     - ebook.springapp
